release: python manage.py migrate --no-input
web: gunicorn --bind :$PORT --workers 4 --worker-class pint.asgi.gunicorn_worker.UvicornWorker pint.asgi:application
celeryworker: celery -A pint --app=pint.celeryconf:app worker --loglevel=info -E
