# Generated by Django 3.2.15 on 2022-10-08 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appextension',
            name='mount',
            field=models.CharField(choices=[('customer_overview_create', 'customer_overview_create'), ('customer_overview_more_actions', 'customer_overview_more_actions'), ('customer_details_more_actions', 'customer_details_more_actions'), ('initiative_overview_create', 'initiative_overview_create'), ('initiative_overview_more_actions', 'initiative_overview_more_actions'), ('initiative_details_more_actions', 'initiative_details_more_actions'), ('navigation_catalog', 'navigation_catalog'), ('navigation_orders', 'navigation_orders'), ('navigation_customers', 'navigation_customers'), ('navigation_discounts', 'navigation_discounts'), ('navigation_translations', 'navigation_translations'), ('navigation_pages', 'navigation_pages')], max_length=256),
        ),
    ]
