# Generated by Django 3.2.15 on 2022-10-31 20:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import pint.thumbnail.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('initiative', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thumbnail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='thumbnails')),
                ('size', models.PositiveIntegerField(validators=[pint.thumbnail.models.validate_thumbnail_size])),
                ('format', models.CharField(blank=True, choices=[('webp', 'WebP')], max_length=32, null=True)),
                ('initiative_media', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thumbnails', to='initiative.initiativemedia')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thumbnails', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
